apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ca2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: {{ .Values.images.frontend | default "ca2-frontend:latest" }}
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
