name: deploy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare kubeconfig
        run: |
          cp /etc/rancher/k3s/k3s.yaml $RUNNER_TEMP/k3s.yaml
          chmod 600 $RUNNER_TEMP/k3s.yaml

      - name: Clean Kubernetes resources
        run: |
          KUBECONFIG=$RUNNER_TEMP/k3s.yaml kubectl delete namespace ca2 || true
          KUBECONFIG=$RUNNER_TEMP/k3s.yaml kubectl wait --for=delete namespace/ca2 --timeout=60s || true

      - name: Deploy with Helm
        run: |
          KUBECONFIG=$RUNNER_TEMP/k3s.yaml helm upgrade --install ca2 ./resources/helm/ca2 -n ca2 --create-namespace
