namespace: ca2

imagePullPolicy: Never

images:
  frontend: ca2-frontend:latest
  productService: ca2-product-service:latest
  orderService: ca2-order-service:latest
  postgres: postgres:15

postgres:
  user: postgres
  password: postgres
  db: orders_db
  storage: 1Gi

servicePorts:
  frontend: 80
  productService: 3001
  orderService: 3002
  postgres: 5432

orderService:
  productServiceUrl: http://product-service:3001
