name: 2_Trivy_Project_Scan

on:
  workflow_dispatch:
  workflow_call:

jobs:
  trivy_project_scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Prepare Trivy cache
        run: |
          mkdir -p ~/.cache/trivy
          mkdir -p trivy-reports

      - name: Trivy scan full project
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          cache-dir: ~/.cache/trivy
          scanners: vuln,secret,misconfig
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: table
          output: trivy-reports/project-scan.txt
          exit-code: '0'

      - name: Upload Trivy project report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-project-report
          path: trivy-reports/project-scan.txt
          if-no-files-found: error
