name: 3_Dependency_Check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  dependency_check:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node dependencies
        run: |
          npm --prefix services/product-service ci
          npm --prefix services/order-service ci
          npm --prefix test ci

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'ca2-order-inventory'
          path: 'services/product-service'
          format: 'HTML'
          args: >
            --scan services/order-service
            --scan test
            --exclude **/*.js
            --failOnCVSS 8

      - name: Upload Dependency Check report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Dependency_Check_Report
          path: ${{ github.workspace }}/reports/dependency-check-report.html
