name: 3_sonarqube

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sonarqube:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          path: coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=donovangong_ca22
            -Dsonar.organization=donovangong
            -Dsonar.projectName="CA2"
            -Dsonar.projectVersion=1.0
            -Dsonar.sources=services,resources
            -Dsonar.tests=test
            -Dsonar.exclusions=**/node_modules/**,**/.git/**,**/coverage/**,**/dist/**,**/build/**
            -Dsonar.test.inclusions=test/**/*.test.js
            -Dsonar.cpd.exclusions=test/**
            -Dsonar.javascript.lcov.reportPaths=coverage/functional-coverage/lcov.info,coverage/api-coverage/lcov.info,coverage/integration-coverage/lcov.info
            -Dsonar.coverage.exclusions=**/server.js,resources/**,test/**
            -Dsonar.sourceEncoding=UTF-8
