name: HQ Control of All workflow

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
    build_deploy:
        name: 1_Build_Deploy
        uses: "./.github/workflows/1_build & deploy.yml"

    
    functional_test:
        name: 2_Functional_Test
        uses: ./.github/workflows/2_functional-test.yml
        needs: build_deploy
    
