name: HQ Control of All workflow

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
    dotnet:
        name: 1_Build 
        uses: ./.github/workflows/build.yml
        #secrets: inherit
    
    
    
    
    deploy:
        name: 4_Deploy
        uses: ./.github/workflows/deploy.yml
        #secrets: inherit     