name: HQ Control of All workflow

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
    build_deploy:
        name: 1_Test_Env_Deploy
        uses: "./.github/workflows/1_build & deploy.yml"
        secrets: inherit

    api_test:
        name: 2_API_Test
        uses: ./.github/workflows/2_api-test.yml
        needs: build_deploy
        secrets: inherit

    integration_test:
        name: 2_Integration_Test
        uses: ./.github/workflows/2_integration-test.yml
        needs: build_deploy
        secrets: inherit

    sonarqube:
        name: 3_SonarQube
        uses: ./.github/workflows/3_sonarqube.yml
        needs:
          - api_test
          - integration_test
        secrets: inherit

    dependency_check:
        name: 3_Dependency_Check
        uses: ./.github/workflows/3_dependency.yml
        needs:
          - api_test
          - integration_test
        secrets: inherit

    monitoring:
        name: 4_Monitoring
        uses: ./.github/workflows/4_monitoring.yml
        needs:
          - sonarqube
          - dependency_check
        secrets: inherit
    
